version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    depends_on:
      - database
    networks:
      - app-network
    ports:
      - '4000:4000'
    command: >
      sh -c "npx prisma migrate deploy && npm start"

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
